version: '3'
services:

  james:
    build:
      context: ..
      dockerfile: james-basic-server/Dockerfile
    image: james-basic-server
    volumes:
      - ./conf:/opt/apache-james/james-basic-server/conf/
      - ./logs:/opt/apache-james/logs/
    environment:
      - JAVA_OPTS=
        -Dlogback.configurationFile="/opt/apache-james/james-basic-server/conf/logback.xml" 
        -Dworking.directory="/opt/apache-james/james-basic-server"
    ports:
      - "9465:465"
      - "9993:993"
    entrypoint: ["james-basic-server"]
